=== uo284247/sew/xml/circuito.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element name="vueltas">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="100"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="longitudType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="250000.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="anchuraType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="anchuraType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="25.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud_coordenadas" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud_coordenadas" type="longitudCoordenadasType" />
	<xs:simpleType name="longitudCoordenadasType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="180.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="latitud" type="latitudType" />
	<xs:simpleType name="latitudType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitudeType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="altitudeType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-20.0"/>
			<xs:maxInclusive value="300.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="distanciaType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="5000.0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== uo284247/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<circuito
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
<nombre>Monza</nombre>
<longitud unidad="metros">5.793</longitud>
<anchura unidad="metros">12</anchura>
<fecha>2024-09-01</fecha>
<hora>15:00:00</hora>
<vueltas>53</vueltas>
<localidad>Monza</localidad>
<pais>Italia</pais>
<referencias>
    <referencia>https://www.clarosports.com/motor/formula-1/gp-de-italia-f1-2024-en-vivo-horario-y-donde-ver-la-carrera-de-formula-1-en-monza-posiciones-y-parrilla-de-salida/</referencia>
    <referencia>https://es.wikipedia.org/wiki/Monza</referencia>
    <referencia>//www.f1-fansite.com/es/circuitos-f1/autodromo-nazionale-monza/</referencia>
</referencias>
<fotos>
    <foto>xml/monza_panoramica.jpeg</foto>
    <foto>xml/monza_recta.jpeg</foto>
    <foto>xml/monza_plano.jpeg</foto>
</fotos>
<videos>
    <video>xml/monza_video.mp4</video>
</videos>
<coordenadas>
    <longitud_coordenadas> 9.281186643752484</longitud_coordenadas>
    <latitud>45.6189736862258</latitud>
    <altitud unidad="metros">184</altitud>
</coordenadas>
<tramos>
    <tramo>
        <distancia unidad="metros">0</distancia>
        <coordenadas>
            <longitud_coordenadas>9.281186643752484</longitud_coordenadas>
            <latitud>45.6189736862258</latitud>
            <altitud unidad="metros">184</altitud>
        </coordenadas>
        <sector>1</sector>
    </tramo>
	<tramo>
		<distancia unidad="metros">612.51</distancia>
		<coordenadas>
			<longitud_coordenadas>9.281898754827951</longitud_coordenadas>
			<latitud>45.62446193689303</latitud>
			<altitud unidad="metros">187</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">13.19</distancia>
		<coordenadas>
			<longitud_coordenadas>9.281992077511372</longitud_coordenadas>
			<latitud>45.62455806635763</latitud>
			<altitud unidad="metros">187</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">31.62</distancia>
		<coordenadas>
			<longitud_coordenadas>9.282396954666055</longitud_coordenadas>
			<latitud>45.62457300181188</latitud>
			<altitud unidad="metros">187</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">18.23</distancia>
		<coordenadas>
			<longitud_coordenadas>9.28247317143523</longitud_coordenadas>
			<latitud>45.6247280948612</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">113.23</distancia>
		<coordenadas>
			<longitud_coordenadas>9.282123017536534</longitud_coordenadas>
			<latitud>45.62571674437242</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">59.94</distancia>
		<coordenadas>
			<longitud_coordenadas>9.282089709098466</longitud_coordenadas>
			<latitud>45.6262554926563</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">143.07</distancia>
		<coordenadas>
			<longitud_coordenadas>9.282247477529445</longitud_coordenadas>
			<latitud>45.62753799623356</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">50.96</distancia>
		<coordenadas>
			<longitud_coordenadas>9.282405893488557</longitud_coordenadas>
			<latitud>45.62798282921435</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">58.56</distancia>
		<coordenadas>
			<longitud_coordenadas>9.28271748677415</longitud_coordenadas>
			<latitud>45.62846221305416</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">71.67</distancia>
		<coordenadas>
			<longitud_coordenadas>9.283281936775449</longitud_coordenadas>
			<latitud>45.62897114148019</latitud>
			<altitud unidad="m  etros">189</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">71.05</distancia>
		<coordenadas>
			<longitud_coordenadas>9.283996381181046</longitud_coordenadas>
			<latitud>45.62936790079348</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">62.82</distancia>
		<coordenadas>
			<longitud_coordenadas>9.284765992018844</longitud_coordenadas>
			<latitud>45.6296519655775</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">86.19</distancia>
		<coordenadas>
			<longitud_coordenadas>9.285823009101886</longitud_coordenadas>
			<latitud>45.62987892728432</latitud>
			<altitud unidad="metros">191</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">286.12</distancia>
		<coordenadas>
			<longitud_coordenadas>9.289478318610144</longitud_coordenadas>
			<latitud>45.63010213948567</latitud>
			<altitud unidad="metros">192</altitud>
		</coordenadas>
		<sector>1</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">148.57</distancia>
		<coordenadas>
			<longitud_coordenadas>9.291380351091419</longitud_coordenadas>
			<latitud>45.6301802116714</latitud>
			<altitud unidad="metros">192</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">11.63</distancia>
		<coordenadas>
			<longitud_coordenadas>9.291484148832501</longitud_coordenadas>
			<latitud>45.63025546107071</latitud>
			<altitud unidad="metros">192</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">35.2</distancia>
		<coordenadas>
			<longitud_coordenadas>9.291630417162049</longitud_coordenadas>
			<latitud>45.63055505823643</latitud>
			<altitud unidad="metros">193</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">82.98</distancia>
		<coordenadas>
			<longitud_coordenadas>9.29267220630698</longitud_coordenadas>
			<latitud>45.63070718674151</latitud>
			<altitud unidad="metros">191</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">219.39</distancia>
		<coordenadas>
			<longitud_coordenadas>9.295338029781707</longitud_coordenadas>
			<latitud>45.63133846016452</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">34.57</distancia>
		<coordenadas>
			<longitud_coordenadas>9.295779081110126</longitud_coordenadas>
			<latitud>45.63136965409519</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">28.91</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296127698919188</longitud_coordenadas>
			<latitud>45.63128107193258</latitud>
			<altitud unidad="metros">190</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">36.06</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296458387128464</longitud_coordenadas>
			<latitud>45.63105429440082</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">20.87</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296556453825586</longitud_coordenadas>
			<latitud>45.63087954615466</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">247.93</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296858072580259</longitud_coordenadas>
			<latitud>45.62865895548179</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">19</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296827162324583</longitud_coordenadas>
			<latitud>45.62848939099064</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">18.76</distancia>
		<coordenadas>
			<longitud_coordenadas>9.296680148796113</longitud_coordenadas>
			<latitud>45.62835572522908</latitud>
			<altitud unidad="metros">189</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">354.02</distancia>
		<coordenadas>
			<longitud_coordenadas>9.29271235297591</longitud_coordenadas>
			<latitud>45.62680803844489</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">48.83</distancia>
		<coordenadas>
			<longitud_coordenadas>9.292190613134558</longitud_coordenadas>
			<latitud>45.62656503658179</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">52.02</distancia>
		<coordenadas>
			<longitud_coordenadas>9.291674535474773</longitud_coordenadas>
			<latitud>45.62626850767877</latitud>
			<altitud unidad="metros">188</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">530.47</distancia>
		<coordenadas>
			<longitud_coordenadas>9.286565780010125</longitud_coordenadas>
			<latitud>45.62311722158494</latitud>
			<altitud unidad="metros">186</altitud>
		</coordenadas>
		<sector>2</sector>
	</tramo>
	<tramo>
		<distancia unidad="metros">61.8</distancia>
		<coordenadas>
			<longitud_coordenadas>9.285956047439791</longitud_coordenadas>
